### ISSUE TITLE
NuGet package

### ISSUE THREAD

**Issue by waynebrantley** [mausch/ElmahFiddler#4]
Make a nuget package out of this.

**Comment by mausch** [comment]
A NuGet package is a release. I wouldn't want to release without at least some basic documentation (see #2). I'd really appreciate it if you could write some docs!

**Comment by waynebrantley** [comment]
Agree, but there are plenty of beta products on there.  I am unable to write docs as I do not know enough about your product options...but like it!

**Comment by mausch** [comment]
Can't do this until Eric Lawrence (author of Fiddler) agrees to have FiddlerCore as a NuGet package https://groups.google.com/d/topic/httpfiddler/NCA3islwKR8/discussion

**Comment by mausch** [comment]
The thread was apparently deleted ( https://groups.google.com/d/msg/httpfiddler/OzjQpuQtOkA/9fa5a_5U7moJ ). Now that Fiddler was bought by Telerik, I guess it's up to them to allow the release of Fiddler Core as a NuGet package.
I'll have to ask again when the new Fiddler website/forum is up.

**Comment by mausch** [comment]
A new thread asking about releasing FiddlerCore as a NuGet package: https://groups.google.com/forum/#!topic/httpfiddler/JjlsC-3qx50

**Comment by mausch** [comment]
I just posted another plea for a NuGet package: http://www.telerik.com/forums/nuget-package-for-fiddlercore

**Comment by mausch** [comment]
After my last nagging, Eric and Telerik agreed to release FiddlerCore as a NuGet package: https://www.nuget.org/packages/FiddlerCore/

And so now I have released ElmahFiddler: https://www.nuget.org/packages/ElmahFiddler/
